### PR TITLE
Update Adafruit_PWMServoDriver.h

### PR DESCRIPTION
**Pull request by sticilface**
use reference to Wire

https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/issues/50

### CODE REVIEW

**Comment by sticilface** [comment]
https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/issues/50

**Comment by ladyada** [comment]
hiya this isn't a great way to fix. if you want to submit a PR, please add a new initializer that only requires the i2c address and defaults to `&Wire` for i2c

**Comment by sticilface** [comment]
> hiya this isn't a great way to fix. if you want to submit a PR, please add a new initializer that only requires the i2c address and defaults to `&Wire` for i2c

Can I ask why passing by reference is not a good idea?  It would prevent subtle bugs where people are able to pass in a hex value thinking it is the i2c addr adds but it is being interpreted as a pointer.  I spent 3hrs wondering why my project was crashing when my code has not changed.  

The pointer underlying Wire in the lib is only set at initialisation so there is no need for runtime changes.  If people are using Wire as a pointer they can just dereference it when passing it in.

**Comment by ladyada** [comment]
have you tried adding a new function for just i2c address passing that takes a uint8_t? your compiler should not be casing an int to a pointer....

**Comment by sticilface** [comment]
I do not think using pointers is safe.  Try the following sketch compiled with standard Arduino IDE for nano:  so a standard compiler that every Arduino user  is using

```cpp
String abc; 

String * test = &abc;   // you can assign the address of string 
String * test2 = 0x45; //  however a standard i2c address is also assignable 
String * test3 = 1;        // surprisingly an int is also assignable 

String & test4 = 1;   //  this does NOT work
String & test5 = abc;  //  This does.  

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

As the example above shows the source of the bug I have filed an issue for is the fact that the standard I2C address is implicitly assignable to a pointer.  
As it stands the constructor:
https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/blob/fa51b6fc8f63b99133b57b3d7b24ac6f9e366bfb/Adafruit_PWMServoDriver.h#L51
```Adafruit_PWMServoDriver(TwoWire *I2C = &Wire, uint8_t addr = 0x40);```

when used as shown in the examples
https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/blob/fa51b6fc8f63b99133b57b3d7b24ac6f9e366bfb/examples/pwmtest/pwmtest.ino#L25
```
// you can also call it with a different address you want
Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver(0x41);
```

Leads to the following initialisation: 
```Adafruit_PWMServoDriver pwm(0x41, 0x40);```

Which will crash!  Thus as it stands the example sketches are broken.  this is a hard to find, subtle bug buried in the default specifications of a class initialiser. 

existing expected behaviour has been changed with introduction of this constructor in https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/commit/a5068e0fc3cb88e0b5222a8d001e121044cdf693#r34198800

I do not think adding another constructor solves the problem.  Passing Wire by reference does.

**Comment by ladyada** [comment]
please try adding another constructor, and let us know what the compiler does!

**Pull request closed without merging**
