### PR TITLE
Replacing '(void)' by '()' for methods which don't have parameters

### PR DESCRIPTION
**Pull request by ulysse314**

### CODE REVIEW

**Comment by ladyada** [comment]
hi thank you for the PR! this is not a change we will merge in, we prefer having void be specific

**Comment by ulysse314** [comment]
Hello,

I'm not sure to understand your answer since reset(), sleep() and wakup() don't have void.

**Comment by ladyada** [comment]
we'd accept a PR to add the 'void' keyword there :)

**Comment by ulysse314** [comment]
Sorry, I can't write such a PR. That's against my religion :)

Do you have an official style guide?

**Pull request closed without merging**
