### PR TITLE
Fix getPWM method and overload getPWM in header

### PR DESCRIPTION
**Pull request by driscollta**
This merge will fix broken getPWM method to actually read two bytes from PWM register, combine into 16 bit value and return. A parameter is needed to specify either the "ON" or "OFF" registers

  An example is provided to test the new getPWM method by writing a value to the register, reading back and comparing the two values.

### CODE REVIEW

**Comment by ladyada** [comment]
hi please remove the main.cpp file

**Comment by driscollta** [comment]
Changed example name to testGetPWM.ino

**Comment by driscollta** [comment]
Changed main.cpp to testGetPWM.ino

**Comment by ladyada** [comment]
the eample has to go in a folder with the same name like all other examples

**Comment by ladyada** [comment]
ok now you need to run clang-format

**Comment by caternuson** [comment]
Closing. I think this was fixed as part of BusIO update. See #56 for more discussion.

**Pull request closed without merging**
